apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-app-api: "thesis/data/production/app-api"
        vault.hashicorp.com/agent-inject-template-app-api: |
          {{- with secret "thesis/data/production/app-api" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: app-api-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/app-api && node server.js"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghtorrent-api-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-ghtorrent-api: "thesis/data/production/ghtorrent-api"
        vault.hashicorp.com/agent-inject-template-ghtorrent-api: |
          {{- with secret "thesis/data/production/ghtorrent-api" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: ghtorrent-api-container
          command: ["/bin/bash", "-c"]
          args: ["source /vault/secrets/ghtorrent-api && ruby app.rb"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-model-api: "thesis/data/production/model-api"
        vault.hashicorp.com/agent-inject-template-model-api: |
          {{- with secret "thesis/data/production/model-api" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: model-api-container
          command: ["/bin/bash", "-c"]
          args: ["source /vault/secrets/model-api && uvicorn main:app --host 0.0.0.0 --port 8000"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-model-training: "thesis/data/production/model-training"
        vault.hashicorp.com/agent-inject-template-model-training: |
          {{- with secret "thesis/data/production/model-training" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: model-training-container
          command: ["/bin/bash", "-c"]
          args: ["source /vault/secrets/model-training && python consumer.py --mode consume"]
