apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IudGgxZW5sbTAyLmxpdmUiOnsidXNlcm5hbWUiOiJyb2JvdCR0aGVzaXMiLCJwYXNzd29yZCI6ImxtYnhnZkp4NG9JbjdIbkxRN2xYbEhGZlVCaWU1ZGt6IiwiYXV0aCI6ImNtOWliM1FrZEdobGMybHpPbXh0WW5oblprcDRORzlKYmpkSWJreFJOMnhZYkVoR1psVkNhV1UxWkd0NiJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor-secret
type: kubernetes.io/dockerconfigjson