apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: model-api-repo
spec:
  image: harbor.th1enlm02.live/staging/CI-build-failure-prediction-inference

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: model-api-img
spec:
  update:
    path: ./manifests/overlays/staging/CI-build-failure-prediction-inference
    strategy: Setters
