apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  namespace: production
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "readonly"
    vault.hashicorp.com/template-static-secret-render-interval: "10s"
    vault.hashicorp.com/agent-inject-secret-ghtorrent-api: "thesis/data/production/ghtorrent-api"
    vault.hashicorp.com/agent-inject-template-ghtorrent-api: |
      {{- with secret "thesis/data/production/ghtorrent-api" -}}
        {{- range $key, $value := .Data.data -}}
          export {{ $key }}="{{ $value }}" \n
        {{- end }}
      {{- end }}

spec:
  serviceAccountName: vault-sa
  containers:
    - name: app
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]
