apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
  labels:
    app: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: model-training-container
          image: harbor.th1enlm02.live/production/ci-build-failure-prediction-models:71d6c5e-1750234033 # {"$imagepolicy": "production:model-training-policy"}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"
