apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
  labels:
    app: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: model-training-container
          image: harbor.th1enlm02.live/production/ci-build-failure-prediction-models:e9253a2-1749894661 # {"$imagepolicy": "production:model-training-policy"}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "600Mi"
              memory: "600Mi"
            limits:
              cpu: "1000m"
              memory: "1000Mi"
