apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: app-api-repo
spec:
  image: harbor.th1enlm02.live/staging/CI-failure-prediction-app

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: app-api-img
spec:
  update:
    path: ./manifests/overlays/staging/CI-failure-prediction-app
    strategy: Setters
