apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api-deployment
  labels:
    app: model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: model-api-container
          image: harbor.th1enlm02.live/production/ci-build-failure-prediction-inference:652377a-1750400324 # {"$imagepolicy": "production:model-api-policy"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"
